# Generated by Django 5.0.7 on 2024-08-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chathistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='role',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='chathistory',
            old_name='content',
            new_name='text',
        ),
    ]
