# Generated by Django 5.0.7 on 2024-08-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_role_chathistory_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='user',
        ),
    ]
