# Generated by Django 5.0.7 on 2024-08-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_chathistory_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='text',
            new_name='content',
        ),
    ]
